"""initial migration

Revision ID: df6bed09ad64
Revises:
Create Date: 2026-03-12 02:48:24.894780

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df6bed09ad64"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gastos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_gastos_usuario_data"))

    with op.batch_alter_table("investimentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_investimentos_user_data"))

    with op.batch_alter_table("receitas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_receitas_usuario_data"))

    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        # add column as nullable first to avoid NOT NULL violation on existing rows
        batch_op.add_column(sa.Column("username", sa.String(), nullable=True))

    # populate `username` from existing `email` values when available
    op.execute("UPDATE usuarios SET username = email WHERE email IS NOT NULL")
    # for any remaining NULL usernames, generate a fallback using the id
    op.execute(
        "UPDATE usuarios SET username = 'user' || id::text WHERE username IS NULL"
    )

    # now create the unique constraint on `username` and drop old columns
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        try:
            batch_op.drop_constraint(
                batch_op.f("usuarios_username_key"), type_="unique"
            )
        except Exception:
            # if the constraint doesn't exist, ignore
            pass
        batch_op.create_unique_constraint(None, ["username"])
        batch_op.drop_column("token")
        batch_op.drop_column("reset_token")
        batch_op.drop_column("reset_token_expires")
        batch_op.drop_column("email")

    # finally, alter column to be NOT NULL now that values are populated
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "reset_token_expires", sa.TEXT(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("reset_token", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("token", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("usuarios_username_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.drop_column("username")

    with op.batch_alter_table("receitas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_receitas_usuario_data"),
            ["usuario_id", "data"],
            unique=False,
        )

    with op.batch_alter_table("investimentos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_investimentos_user_data"),
            ["usuario_id", "data"],
            unique=False,
        )

    with op.batch_alter_table("gastos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_gastos_usuario_data"), ["usuario_id", "data"], unique=False
        )

    # ### end Alembic commands ###
